import { Header } from "@/components/lib/Header";
import Head from "next/head";
import "@/styles/globals.css";
import { Footer } from "@/components/lib/Footer";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Fahad&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-screen-2xl mx-auto flex-col align-center justify-center bg-white px-5">
        <Header />
        <Component {...pageProps} />
        <Footer />
      </div>
    </>
  );
}
